CREATE DATABASE db_rpj;

CREATE TABLE t_usuario(
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(40) NOT NULL,
	email VARCHAR(40) NOT NULL UNIQUE,
	senha VARCHAR(64) NOT NULL
);

CREATE TABLE t_produto(
	id INT(3) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(40) NOT NULL,
	preco INT(10) UNSIGNED,
	marca VARCHAR(40) NOT NULL
);

